"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_surface0)\
$username\
[](bg:color_peach fg:color_surface0)\
$directory\
[](fg:color_peach bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_teal)\
$c\
$rust\
$golang\
$python\
[](fg:color_teal bg:color_blue)\
$time\
[ ](fg:color_blue)\
$line_break$character"""

palette = 'catpuccin_machiatto'

[palettes.catpuccin_machiatto]
color_rosewater = "#f4dbd6"
color_flamingo  = "#f0c6c6"
color_pink      = "#f5bde6"
color_mauve     = "#c6a0f6"
color_red       = "#ed8796"
color_maroon    = "#ee99a0"
color_peach     = "#f5a97f"
color_yellow    = "#eed49f"
color_green     = "#a6da95"
color_teal      = "#8bd5ca"
color_sky       = "#91d7e3"
color_sapphire  = "#7dc4e4"
color_blue      = "#8aadf4"
color_lavender  = "#b7bdf8"
color_text      = "#cad3f5"
color_subtext1  = "#b8c0e0"
color_subtext0  = "#a5adcb"
color_overlay2  = "#939ab7"
color_overlay1  = "#8087a2"
color_overlay0  = "#6e738d"
color_surface2  = "#5b6078"
color_surface1  = "#494d64"
color_surface0  = "#363a4f"
color_base      = "#24273a"
color_mantle    = "#1e2030"
color_crust     = "#181926"

[username]
show_always = true
style_user = "bg:color_surface0 fg:color_text"
style_root = "bg:color_surface0 fg:color_text"
format = '[󰊠 $user ]($style)'

[directory]
style = "fg:color_mantle bg:color_peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"dev" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_mantle bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
untracked = '?${count}'
stashed = '$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘ ${count}'
format = '[[($all_status$ahead_behind )](fg:color_mantle bg:color_green)]($style)'

[c]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mantle bg:color_teal)]($style)'

[rust]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mantle bg:color_teal)]($style)'

[golang]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mantle bg:color_teal)]($style)'

[python]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mantle bg:color_teal)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_blue"
format = '[[  $time ](fg:color_mantle bg:color_blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
