"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break$character"""

palette = 'catpuccin_machiatto'

[palettes.catpuccin_machiatto]
color_rosewater = "#f4dbd6"
color_flamingo  = "#f0c6c6"
color_pink      = "#f5bde6"
color_mauve     = "#c6a0f6"
color_red       = "#ed8796"
color_maroon    = "#ee99a0"
color_peach     = "#f5a97f"
color_yellow    = "#eed49f"
color_green     = "#a6da95"
color_teal      = "#8bd5ca"
color_sky       = "#91d7e3"
color_sapphire  = "#7dc4e4"
color_blue      = "#8aadf4"
color_lavender  = "#b7bdf8"
color_text      = "#cad3f5"
color_subtext1  = "#b8c0e0"
color_subtext0  = "#a5adcb"
color_overlay2  = "#939ab7"
color_overlay1  = "#8087a2"
color_overlay0  = "#6e738d"
color_surface2  = "#5b6078"
color_surface1  = "#494d64"
color_surface0  = "#363a4f"
color_base      = "#24273a"
color_mantle    = "#1e2030"
color_crust     = "#181926"

[username]
show_always = true
style_user = "bg:color_surface0 fg:color_text"
style_root = "bg:color_surface0 fg:color_text"
format = '[$user ](#d8dee9)'

[directory]
style = "fg:color_mantle bg:color_peach"
format = "[\\[   $path \\]](#ebcb8b)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"dev" = "󰲋 "

[git_branch]
symbol = ""
format = '[ \(](#a3be8c)[ $symbol $branch](#a3be8c)'

[git_state]
format = '[\($state( $progress_current/$progress_total)\)](#a3be8c)'

[git_status]
style = "bg:color_green"
conflicted = ' =${count}'
untracked = ' ?${count}'
stashed = ' \$${count}'
modified = ' !${count}'
staged = ' +${count}'
renamed = ' »${count}'
deleted = ' ✘ ${count}'
ahead = ' ⇡${count}'
behind = ' ⇣${count}'
format = '[$all_status$ahead_behind](#a3be8c)[ \)](#a3be8c)'
[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
