[terminal.shell]
program = "/usr/bin/zsh"
args    = ["-l"]

[env]
TERM = "xterm-256color"

[window]
padding      = { x = 4, y = 0 }
startup_mode = "Maximized"

[font]
normal      = { family = "JetBrainsMonoNL NF", style = "SemiBold" }
bold        = { family = "JetBrainsMonoNL NF", style = "Bold" }
italic      = { family = "JetBrainsMonoNL NF", style = "SemiBold Italic" }
bold_italic = { family = "JetBrainsMonoNL NF", style = "Bold Italic" }
size        = 13

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'

[general]
live_config_reload = true
